Gh 1
deeplime-io/onecode pull request #6
Opened 2023-03-09 15:19 UTC by hameye

2023-03-16 11:15 UTC, theweaklink requested changes
Also missing:
- add `emulations` tests too (see FileInput)

2023-03-16 11:15 UTC, theweaklink commented on onecode/elements/input/folder_input.py
> +
add another check `is_dir` otherwise raise `NotADirectoryError`

2023-03-16 11:15 UTC, theweaklink commented on onecode/elements/input/folder_input.py
> +
it should be directly `_validate()`. Internal `_validate_folder_value()` is not required since there is no `multiple` to handle

In that case, type of `value` should be `str`

2023-03-16 11:15 UTC, theweaklink commented on tests/utils/flow_cli.py
> +    flow: str,
why `flow` ?

2023-03-16 14:39 UTC, theweaklink commented on tests/utils/flow_cli.py
> +    flow: str,
that's fine, otherwise we should probably update the other functions too.
However in hindsights, it may not be necessary to have a function just for 1 statement `os.makedirs(flow, exist_ok=True)` ?

2023-03-16 14:49 UTC, hameye commented on tests/utils/flow_cli.py
> +    flow: str,
@theweaklink fair enough

2023-03-17 12:16 UTC, theweaklink approved these changes

2023-03-17 12:16 UTC, merged