Gh 5: Fix NeuralNetInput Dropdown
deeplime-io/onecode pull request #8
Opened 2023-03-17 10:55 UTC by hameye

![Screenshot 2023-03-17 at 11-53-59 app · Streamlit](https://user-images.githubusercontent.com/57682091/225885714-8bfe2f11-fa79-4eb1-9b41-5ae86437a0d0.png)

2023-03-24 08:13 UTC, theweaklink requested changes
Issue with the case without `count`

2023-03-24 08:13 UTC, theweaklink commented on examples/DeepLearning/flows/onecode_ext/input_elements/neural_net_input.py
> +    {option_id} = 0
the `else` part will not work because if there is no count, we're no longer dealing with a list:
```python
    nn = neural_net_input(
        'Neural Net',
        {"neurons": 32, "activation": "relu", "dropout": 0.2}
    )
```

2023-03-27 07:01 UTC, hameye commented on examples/DeepLearning/flows/onecode_ext/input_elements/neural_net_input.py
> +    {option_id} = 0
@theweaklink would it be better then to put it in a list in the function ? 
This is easier than dealing with a dict and split the all the computation depending on the tye.

2023-03-27 08:55 UTC, hameye commented on examples/DeepLearning/flows/onecode_ext/input_elements/neural_net_input.py
> +    {option_id} = 0
@theweaklink I meant in the internal behviour of the function, we can directly convert it as a list

2023-03-27 11:32 UTC, theweaklink commented on examples/DeepLearning/flows/onecode_ext/input_elements/neural_net_input.py
> +    {option_id} = 0
ok I didn't understand. Yes, you can change the internal mechanics of the NeuralNetInput for sure. Something like that?

```python
value = self.value if type(value) == list else [self.value]
```

2023-04-04 07:13 UTC, theweaklink approved these changes

2023-04-04 07:13 UTC, merged